#!/bin/sh
#
# Salt minion
###################################

# LSB header

### BEGIN INIT INFO
# Provides: salt-minion
# Required-Start: network
# Short-Description: salt minion control daemon
# Description: This is a daemon that controls the salt minions
### END INIT INFO

# chkconfig header

# chkconfig: 345 99 01
# description:  This is a daemon that controls the salt mininons
#
# processname: /usr/local/bin/salt-minion

SALTMINION=/usr/local/bin/salt-minion
PYTHON=/usr/local/bin/python

# Sanity checks.
[ -x $SALTMINION ] || exit 0

DEBIAN_VERSION=/etc/debian_version
SUSE_RELEASE=/etc/SuSE-release
# Source function library.
if [ -f $DEBIAN_VERSION ]; then
   break   
elif [ -f $SUSE_RELEASE -a -r /etc/rc.status ]; then
    . /etc/rc.status
else
    . /etc/rc.d/init.d/functions
fi

SERVICE=salt-minion
PROCESS=salt-minion
CONFIG_ARGS="-c /talksum/salt/minion"
PIDFILE=/talksum/salt/minion/var/run/salt-minion.pid

RETVAL=0

start() {
    echo -n $"Starting TalkOS salt-minion daemon: "
    if [ -f $SUSE_RELEASE ]; then
        startproc -f -p $PIDFILE $SALTMINION -d $CONFIG_ARGS
        rc_status -v
    elif [ -e $DEBIAN_VERSION ]; then
        if [ -f $LOCKFILE ]; then
            echo -n "already started, lock file found" 
            RETVAL=1
        elif $PYTHON $SALTMINION --pid-file $PIDFILE -d; then
            echo -n "OK"
            RETVAL=0
        fi
    else
        daemon --pidfile=$PIDFILE --check $SERVICE $SALTMINION -d $CONFIG_ARGS --pid-file $PIDFILE
    fi
    RETVAL=$?
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping TalkOS salt-minion daemon: "
    if [ -f $SUSE_RELEASE ]; then
        killproc -p $PIDFILE -TERM $SALTMINION
        rc_status -v
    elif [ -f $DEBIAN_VERSION ]; then
        # Added this since Debian's start-stop-daemon doesn't support spawned processes
        if ps -ef | grep "$PYTHON $SALTMINION" | grep -v grep | awk '{print $2}' | xargs kill &> /dev/null; then
            echo -n "OK"
            RETVAL=0
        else
            echo -n "Daemon is not started"
            RETVAL=1
        fi
    else
        killproc -p $PIDFILE $PROCESS
    fi
    RETVAL=$?
    echo
}

restart() {
   stop
   start
}

# See how we were called.
case "$1" in
    start|stop|restart)
        $1
        ;;
    status)
        if [ -f $SUSE_RELEASE ]; then
            echo -n "Checking for service salt-minion "
            checkproc $SALTMINION
            rc_status -v
        elif [ -f $DEBIAN_VERSION ]; then
            if [ -f $LOCKFILE ]; then
                RETVAL=0
                echo "TalkOS salt-minion is running."
            else
                RETVAL=1
                echo "TalkOS salt-minion is stopped."
            fi
        else
            status -p $PIDFILE $PROCESS
            RETVAL=$?
        fi
        ;;
    condrestart)
        [ -f $LOCKFILE ] && restart || :
        ;;
    reload)
        echo "can't reload configuration, you have to restart it"
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
        exit 1
        ;;
esac
exit $RETVAL

